development:
  # adapter: async
  adapter: redis
  url: <%=ENV["REDIS_URL"]%>

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: rails_custom_login_production
