:schedule:
  example_cron_job: 
    name: 'Hard worker - every 1min'
    namespace: 'Foo'
    cron: '*/1 * * * *'
    class: "Example::CronJob"
  
  send_reminder_every_minute: 
    cron: "*/1 * * * *"
    class: "HelloJob" 
    args: ["user@example.com"]
    description: "Send reminder emails every minute"
